set -g default-terminal "screen-256color"
set -as terminal-features ",xterm*:RGB"

set -g @plugin "arcticicestudio/nord-tmux"
set -g prefix C-Space
unbind C-b
bind-key C-Space send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind m

set -g base-index 1 
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

unbind r 
bind r source-file ~/.config/tmux/tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

bind -n C-n next-window
bind -n C-p previous-window
bind -n C-f run-shell "tmux neww ~/.env/bin/tmux-sessionizer"


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# set -g @plugin "arcoticicestudio/nord-tmux"
# set -g @themepack "basic"

#set -g @plugin 'catppuccin/tmux'
#set -g @catppuccin_flavour 'macchiato'
# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum 'on'

set -g mouse on
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel

unbind -T copy-mode-vi MouseDragEnd1Pane

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run '~/.tmux/plugins/tpm/tpm'

set -g automatic-rename off
set -g allow-rename off

# Base style
set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-style fg=#E5E9F0,bg=#4C566A

# left
set -g status-left-length 20
set -g status-left '#[bg=#2E3440,fg=#E5E9F0]#[bold][#S] '

# window list
set -g window-status-separator ' '
set -g window-status-style fg=colour70,bg=colour236
set -g window-status-format '#[bg=#3B4252,fg=#A3BE8C,bold] #I • #[bold,bg=#2E3440,fg=#A3BE8C]#W '   # inactive: dim index, bright name

# current window
set -g window-status-current-format '#[bold,bg=#5E81AC,fg=#E5E9F0]#I ❯ #W'

# right: "host" HH:MM DD-Mon-YY
set -g status-right-length 40
set -g status-right '#[bg=#2E3440,fg=#E5E9F0]"#H" %H:%M %d-%b-%y'

# subtle activity underline
set -g window-status-activity-style underscore
set -g visual-activity on
